"""Initial migration

Revision ID: 5416b6d7a971
Revises: 
Create Date: 2024-12-07 15:41:13.573652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5416b6d7a971'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'first_name',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('authors', 'last_name',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('authors', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('authors', 'nationality',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
    #op.create_index(op.f('ix_authors_first_name'), 'authors', ['first_name'], unique=False)
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    #op.create_index(op.f('ix_authors_last_name'), 'authors', ['last_name'], unique=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('books', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'category',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('books', 'file_path',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    #op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'file_path',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('books', 'category',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('books', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_index(op.f('ix_authors_last_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_first_name'), table_name='authors')
    op.alter_column('authors', 'nationality',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('authors', 'date_of_birth',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('authors', 'last_name',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('authors', 'first_name',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
